services:
  app1:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=3001
    networks:
      - loadBalancer

  app2:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=3002
    networks:
      - loadBalancer

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:8080"
    networks:
      - loadBalancer
    depends_on:
      - app1
      - app2

networks:
  loadBalancer:
    driver: bridge