services:
  # Aplicación Node.js en dos instancias
  app1:
    image: jpcastano/cineplus:backendv1
    environment:
      - PORT=3000
    networks:
      - loadBalancer

  app2:
    image: jpcastano/cineplus:backendv1
    environment:
      - PORT=3001
    networks:
      - loadBalancer

  app3:
    image: jpcastano/cineplus:backendv1
    environment:
      - PORT=3002
    networks:
      - loadBalancer

  app4:
    image: jpcastano/cineplus:backendv1
    environment:
      - PORT=3003
    networks:
      - loadBalancer

  app5:
    image: jpcastano/cineplus:backendv1
    environment:
      - PORT=3004
    networks:
      - loadBalancer

  front:
    image: jpcastano/cineplus:apienlocalhost80
    ports:
      - 6969:80

  VMfront:
    image: jpcastano/cineplus:apienvm
    ports:
      - 9696:80


  # Balanceador de carga Nginx
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:8080
    networks:
      - loadBalancer
    depends_on:
      - app1
      - app2

networks:
  loadBalancer:
    driver: bridge