config:
  target: "http://localhost"  # URL del balanceador
  phases:
    - duration: 60
      arrivalRate: 5
      name: "Fase de calentamiento"
    - duration: 120
      arrivalRate: 10
      rampTo: 50
      name: "Incremento gradual de carga"
    - duration: 180
      arrivalRate: 50
      name: "Prueba de carga sostenida"
  defaults:
    headers:
      User-Agent: "Artillery Load Test"
      Content-Type: "application/json"

scenarios:
  - name: "Prueba de listado de productos"
    flow:
      - get:
          url: "/api/listarProductos"
          expect:
            - statusCode: 200
      - think: 1  # Pausa de 1 segundo entre requests

  - name: "Crear usuario con datos únicos"
    flow:
      - loop:
        - post:
            url: "/api/crearUsuario"
            json:
              email: "usuario_{{$randomNumber(1,1000000)}}_{{ $randomString(5) }}@example.com"              
              password: "password123"
            expect:
              - statusCode: 201
        - think: 1  # Pausa de 1 segundo entre requests

# graficar tests: 
# artillery run -o report.json productos-test.yml
# artillery report report.json
